/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AgentsRouteImport } from './routes/agents'
import { Route as HallRouteImport } from './routes/hall'
import { Route as InboxRouteImport } from './routes/inbox'
import { Route as KnowledgeRouteImport } from './routes/knowledge'
import { Route as LoadoutsRouteImport } from './routes/loadouts'
import { Route as McpServersRouteImport } from './routes/mcp-servers'
import { Route as ProvidersRouteImport } from './routes/providers'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as ToolsRouteImport } from './routes/tools'
import { Route as ProjectsIndexRouteImport } from './routes/projects.index'
import { Route as ProjectsIdRouteImport } from './routes/projects.$id'
import { Route as RunsIndexRouteImport } from './routes/runs.index'
import { Route as RunsIdRouteImport } from './routes/runs.$id'
import { Route as SkillsIndexRouteImport } from './routes/skills.index'
import { Route as SkillsIdRouteImport } from './routes/skills.$id'
import { Route as TasksIndexRouteImport } from './routes/tasks.index'
import { Route as TasksIdRouteImport } from './routes/tasks.$id'
import { Route as WorkflowsIndexRouteImport } from './routes/workflows.index'
import { Route as WorkflowsIdRouteImport } from './routes/workflows.$id'
import { Route as ProjectsIdGraphRouteImport } from './routes/projects.$id_.graph'
import { Route as ProjectsIdKnowledgeRouteImport } from './routes/projects.$id_.knowledge'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AgentsRoute = AgentsRouteImport.update({
  id: '/agents',
  path: '/agents',
  getParentRoute: () => rootRouteImport,
} as any)
const HallRoute = HallRouteImport.update({
  id: '/hall',
  path: '/hall',
  getParentRoute: () => rootRouteImport,
} as any)
const InboxRoute = InboxRouteImport.update({
  id: '/inbox',
  path: '/inbox',
  getParentRoute: () => rootRouteImport,
} as any)
const KnowledgeRoute = KnowledgeRouteImport.update({
  id: '/knowledge',
  path: '/knowledge',
  getParentRoute: () => rootRouteImport,
} as any)
const LoadoutsRoute = LoadoutsRouteImport.update({
  id: '/loadouts',
  path: '/loadouts',
  getParentRoute: () => rootRouteImport,
} as any)
const McpServersRoute = McpServersRouteImport.update({
  id: '/mcp-servers',
  path: '/mcp-servers',
  getParentRoute: () => rootRouteImport,
} as any)
const ProvidersRoute = ProvidersRouteImport.update({
  id: '/providers',
  path: '/providers',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const ToolsRoute = ToolsRouteImport.update({
  id: '/tools',
  path: '/tools',
  getParentRoute: () => rootRouteImport,
} as any)
const ProjectsIndexRoute = ProjectsIndexRouteImport.update({
  id: '/projects/',
  path: '/projects/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProjectsIdRoute = ProjectsIdRouteImport.update({
  id: '/projects/$id',
  path: '/projects/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const RunsIndexRoute = RunsIndexRouteImport.update({
  id: '/runs/',
  path: '/runs/',
  getParentRoute: () => rootRouteImport,
} as any)
const RunsIdRoute = RunsIdRouteImport.update({
  id: '/runs/$id',
  path: '/runs/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const SkillsIndexRoute = SkillsIndexRouteImport.update({
  id: '/skills/',
  path: '/skills/',
  getParentRoute: () => rootRouteImport,
} as any)
const SkillsIdRoute = SkillsIdRouteImport.update({
  id: '/skills/$id',
  path: '/skills/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const TasksIndexRoute = TasksIndexRouteImport.update({
  id: '/tasks/',
  path: '/tasks/',
  getParentRoute: () => rootRouteImport,
} as any)
const TasksIdRoute = TasksIdRouteImport.update({
  id: '/tasks/$id',
  path: '/tasks/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const WorkflowsIndexRoute = WorkflowsIndexRouteImport.update({
  id: '/workflows/',
  path: '/workflows/',
  getParentRoute: () => rootRouteImport,
} as any)
const WorkflowsIdRoute = WorkflowsIdRouteImport.update({
  id: '/workflows/$id',
  path: '/workflows/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const ProjectsIdGraphRoute = ProjectsIdGraphRouteImport.update({
  id: '/projects/$id_/graph',
  path: '/projects/$id/graph',
  getParentRoute: () => rootRouteImport,
} as any)
const ProjectsIdKnowledgeRoute = ProjectsIdKnowledgeRouteImport.update({
  id: '/projects/$id_/knowledge',
  path: '/projects/$id/knowledge',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/agents': typeof AgentsRoute
  '/hall': typeof HallRoute
  '/inbox': typeof InboxRoute
  '/knowledge': typeof KnowledgeRoute
  '/loadouts': typeof LoadoutsRoute
  '/mcp-servers': typeof McpServersRoute
  '/providers': typeof ProvidersRoute
  '/settings': typeof SettingsRoute
  '/tools': typeof ToolsRoute
  '/projects/$id': typeof ProjectsIdRoute
  '/runs/$id': typeof RunsIdRoute
  '/skills/$id': typeof SkillsIdRoute
  '/tasks/$id': typeof TasksIdRoute
  '/workflows/$id': typeof WorkflowsIdRoute
  '/projects/': typeof ProjectsIndexRoute
  '/runs/': typeof RunsIndexRoute
  '/skills/': typeof SkillsIndexRoute
  '/tasks/': typeof TasksIndexRoute
  '/workflows/': typeof WorkflowsIndexRoute
  '/projects/$id/graph': typeof ProjectsIdGraphRoute
  '/projects/$id/knowledge': typeof ProjectsIdKnowledgeRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/agents': typeof AgentsRoute
  '/hall': typeof HallRoute
  '/inbox': typeof InboxRoute
  '/knowledge': typeof KnowledgeRoute
  '/loadouts': typeof LoadoutsRoute
  '/mcp-servers': typeof McpServersRoute
  '/providers': typeof ProvidersRoute
  '/settings': typeof SettingsRoute
  '/tools': typeof ToolsRoute
  '/projects/$id': typeof ProjectsIdRoute
  '/runs/$id': typeof RunsIdRoute
  '/skills/$id': typeof SkillsIdRoute
  '/tasks/$id': typeof TasksIdRoute
  '/workflows/$id': typeof WorkflowsIdRoute
  '/projects': typeof ProjectsIndexRoute
  '/runs': typeof RunsIndexRoute
  '/skills': typeof SkillsIndexRoute
  '/tasks': typeof TasksIndexRoute
  '/workflows': typeof WorkflowsIndexRoute
  '/projects/$id/graph': typeof ProjectsIdGraphRoute
  '/projects/$id/knowledge': typeof ProjectsIdKnowledgeRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/agents': typeof AgentsRoute
  '/hall': typeof HallRoute
  '/inbox': typeof InboxRoute
  '/knowledge': typeof KnowledgeRoute
  '/loadouts': typeof LoadoutsRoute
  '/mcp-servers': typeof McpServersRoute
  '/providers': typeof ProvidersRoute
  '/settings': typeof SettingsRoute
  '/tools': typeof ToolsRoute
  '/projects/$id': typeof ProjectsIdRoute
  '/runs/$id': typeof RunsIdRoute
  '/skills/$id': typeof SkillsIdRoute
  '/tasks/$id': typeof TasksIdRoute
  '/workflows/$id': typeof WorkflowsIdRoute
  '/projects/': typeof ProjectsIndexRoute
  '/runs/': typeof RunsIndexRoute
  '/skills/': typeof SkillsIndexRoute
  '/tasks/': typeof TasksIndexRoute
  '/workflows/': typeof WorkflowsIndexRoute
  '/projects/$id_/graph': typeof ProjectsIdGraphRoute
  '/projects/$id_/knowledge': typeof ProjectsIdKnowledgeRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/agents'
    | '/hall'
    | '/inbox'
    | '/knowledge'
    | '/loadouts'
    | '/mcp-servers'
    | '/providers'
    | '/settings'
    | '/tools'
    | '/projects/$id'
    | '/runs/$id'
    | '/skills/$id'
    | '/tasks/$id'
    | '/workflows/$id'
    | '/projects/'
    | '/runs/'
    | '/skills/'
    | '/tasks/'
    | '/workflows/'
    | '/projects/$id/graph'
    | '/projects/$id/knowledge'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/agents'
    | '/hall'
    | '/inbox'
    | '/knowledge'
    | '/loadouts'
    | '/mcp-servers'
    | '/providers'
    | '/settings'
    | '/tools'
    | '/projects/$id'
    | '/runs/$id'
    | '/skills/$id'
    | '/tasks/$id'
    | '/workflows/$id'
    | '/projects'
    | '/runs'
    | '/skills'
    | '/tasks'
    | '/workflows'
    | '/projects/$id/graph'
    | '/projects/$id/knowledge'
  id:
    | '__root__'
    | '/'
    | '/agents'
    | '/hall'
    | '/inbox'
    | '/knowledge'
    | '/loadouts'
    | '/mcp-servers'
    | '/providers'
    | '/settings'
    | '/tools'
    | '/projects/$id'
    | '/runs/$id'
    | '/skills/$id'
    | '/tasks/$id'
    | '/workflows/$id'
    | '/projects/'
    | '/runs/'
    | '/skills/'
    | '/tasks/'
    | '/workflows/'
    | '/projects/$id_/graph'
    | '/projects/$id_/knowledge'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AgentsRoute: typeof AgentsRoute
  HallRoute: typeof HallRoute
  InboxRoute: typeof InboxRoute
  KnowledgeRoute: typeof KnowledgeRoute
  LoadoutsRoute: typeof LoadoutsRoute
  McpServersRoute: typeof McpServersRoute
  ProvidersRoute: typeof ProvidersRoute
  SettingsRoute: typeof SettingsRoute
  ToolsRoute: typeof ToolsRoute
  ProjectsIdRoute: typeof ProjectsIdRoute
  RunsIdRoute: typeof RunsIdRoute
  SkillsIdRoute: typeof SkillsIdRoute
  TasksIdRoute: typeof TasksIdRoute
  WorkflowsIdRoute: typeof WorkflowsIdRoute
  ProjectsIndexRoute: typeof ProjectsIndexRoute
  RunsIndexRoute: typeof RunsIndexRoute
  SkillsIndexRoute: typeof SkillsIndexRoute
  TasksIndexRoute: typeof TasksIndexRoute
  WorkflowsIndexRoute: typeof WorkflowsIndexRoute
  ProjectsIdGraphRoute: typeof ProjectsIdGraphRoute
  ProjectsIdKnowledgeRoute: typeof ProjectsIdKnowledgeRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/agents': {
      id: '/agents'
      path: '/agents'
      fullPath: '/agents'
      preLoaderRoute: typeof AgentsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/hall': {
      id: '/hall'
      path: '/hall'
      fullPath: '/hall'
      preLoaderRoute: typeof HallRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/inbox': {
      id: '/inbox'
      path: '/inbox'
      fullPath: '/inbox'
      preLoaderRoute: typeof InboxRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/knowledge': {
      id: '/knowledge'
      path: '/knowledge'
      fullPath: '/knowledge'
      preLoaderRoute: typeof KnowledgeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/loadouts': {
      id: '/loadouts'
      path: '/loadouts'
      fullPath: '/loadouts'
      preLoaderRoute: typeof LoadoutsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mcp-servers': {
      id: '/mcp-servers'
      path: '/mcp-servers'
      fullPath: '/mcp-servers'
      preLoaderRoute: typeof McpServersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/providers': {
      id: '/providers'
      path: '/providers'
      fullPath: '/providers'
      preLoaderRoute: typeof ProvidersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tools': {
      id: '/tools'
      path: '/tools'
      fullPath: '/tools'
      preLoaderRoute: typeof ToolsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/projects/': {
      id: '/projects/'
      path: '/projects'
      fullPath: '/projects/'
      preLoaderRoute: typeof ProjectsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/projects/$id': {
      id: '/projects/$id'
      path: '/projects/$id'
      fullPath: '/projects/$id'
      preLoaderRoute: typeof ProjectsIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/runs/': {
      id: '/runs/'
      path: '/runs'
      fullPath: '/runs/'
      preLoaderRoute: typeof RunsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/runs/$id': {
      id: '/runs/$id'
      path: '/runs/$id'
      fullPath: '/runs/$id'
      preLoaderRoute: typeof RunsIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/skills/': {
      id: '/skills/'
      path: '/skills'
      fullPath: '/skills/'
      preLoaderRoute: typeof SkillsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/skills/$id': {
      id: '/skills/$id'
      path: '/skills/$id'
      fullPath: '/skills/$id'
      preLoaderRoute: typeof SkillsIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tasks/': {
      id: '/tasks/'
      path: '/tasks'
      fullPath: '/tasks/'
      preLoaderRoute: typeof TasksIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tasks/$id': {
      id: '/tasks/$id'
      path: '/tasks/$id'
      fullPath: '/tasks/$id'
      preLoaderRoute: typeof TasksIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/workflows/': {
      id: '/workflows/'
      path: '/workflows'
      fullPath: '/workflows/'
      preLoaderRoute: typeof WorkflowsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/workflows/$id': {
      id: '/workflows/$id'
      path: '/workflows/$id'
      fullPath: '/workflows/$id'
      preLoaderRoute: typeof WorkflowsIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/projects/$id_/graph': {
      id: '/projects/$id_/graph'
      path: '/projects/$id/graph'
      fullPath: '/projects/$id/graph'
      preLoaderRoute: typeof ProjectsIdGraphRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/projects/$id_/knowledge': {
      id: '/projects/$id_/knowledge'
      path: '/projects/$id/knowledge'
      fullPath: '/projects/$id/knowledge'
      preLoaderRoute: typeof ProjectsIdKnowledgeRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AgentsRoute: AgentsRoute,
  HallRoute: HallRoute,
  InboxRoute: InboxRoute,
  KnowledgeRoute: KnowledgeRoute,
  LoadoutsRoute: LoadoutsRoute,
  McpServersRoute: McpServersRoute,
  ProvidersRoute: ProvidersRoute,
  SettingsRoute: SettingsRoute,
  ToolsRoute: ToolsRoute,
  ProjectsIdRoute: ProjectsIdRoute,
  RunsIdRoute: RunsIdRoute,
  SkillsIdRoute: SkillsIdRoute,
  TasksIdRoute: TasksIdRoute,
  WorkflowsIdRoute: WorkflowsIdRoute,
  ProjectsIndexRoute: ProjectsIndexRoute,
  RunsIndexRoute: RunsIndexRoute,
  SkillsIndexRoute: SkillsIndexRoute,
  TasksIndexRoute: TasksIndexRoute,
  WorkflowsIndexRoute: WorkflowsIndexRoute,
  ProjectsIdGraphRoute: ProjectsIdGraphRoute,
  ProjectsIdKnowledgeRoute: ProjectsIdKnowledgeRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
