/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/v1/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Saúde da API
         * @description Reporta o estado do processo e o resultado de um `SELECT 1` no PostgreSQL. Responde 200 mesmo com o banco fora, com `status: degraded`, para que a diferença entre 'processo caiu' e 'dependência caiu' fique visível.
         */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Estado atual da API e do banco. */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["HealthResponse"];
                    };
                };
                /** @description Falha inesperada. */
                500: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/problem+json": components["schemas"]["ProblemDetails"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** @description Saúde da API e de suas dependências. */
        HealthResponse: {
            status: components["schemas"]["HealthStatus"];
            /** @description Nome do processo que respondeu. */
            service: string;
            /** @description Versão do pacote da API. */
            version: string;
            /** @description Segundos desde o boot do processo. */
            uptimeSeconds: number;
            /**
             * Format: date-time
             * @description Instante da checagem, em UTC (ISO 8601).
             */
            checkedAt: string;
            database: components["schemas"]["DatabaseHealth"];
        };
        /** @enum {string} */
        HealthStatus: "ok" | "degraded";
        /** @description Estado da conexão com o banco. */
        DatabaseHealth: {
            /** @description Verdadeiro quando o `SELECT 1` respondeu. */
            ok: boolean;
            /** @description Tempo da consulta, em milissegundos. */
            latencyMs: number;
            /** @description Mensagem do erro quando a consulta falhou; nulo caso contrário. */
            error: string | null;
        };
        /** @description Erro no formato RFC 9457 (`application/problem+json`). */
        ProblemDetails: {
            /** @description URI que identifica o tipo do problema. `about:blank` quando genérico. */
            type: string;
            /** @description Resumo curto e estável do tipo do problema. */
            title: string;
            /** @description Código HTTP da resposta. */
            status: number;
            /** @description Explicação específica desta ocorrência. */
            detail: string;
            /** @description URI da ocorrência: o caminho da requisição. */
            instance: string;
            /** @description Identificador da requisição, para casar com os logs. */
            requestId?: string;
            /** @description Presente quando a validação de entrada falhou. */
            errors?: components["schemas"]["ValidationIssue"][];
        };
        ValidationIssue: {
            /** @description Caminho do campo com problema, em notação de ponto. Vazio para a raiz. */
            path: string;
            /** @description Descrição legível do problema. */
            message: string;
            /** @description Código do problema, vindo do schema Zod. */
            code: string;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export type operations = Record<string, never>;
